apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifest
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 3
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkinstest
          image: killerquen69/gradlespringboot:67
          ports:
            - containerPort: 8080



