apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbtest

spec:
  selector:
    matchLabels:
      app: mongotest
  template:
    metadata:
      labels:
        app: mongotest
    spec:
      containers:
        - name: mongoose
          image: mongodb/mongodb-community-server
          ports:
            - containerPort: 27017

