apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxtest
  namespace: meta

spec:
  selector:
    matchLabels:
      app: nginxtest
  replicas: 3
  template:
    metadata:
      labels:
        app: nginxtest
    spec:
      containers:
        - name: nginxx
          image: nginx
          ports:
            - containerPort: 80

